POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker 55",
  "description": "Teste de descrição"

}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/50f32431-7b24-4c7f-9cd9-9b7c1e97ecdc
